%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
Camera1.fx: 848.529
Camera1.fy: 848.141
Camera1.cx: 479.882
Camera1.cy: 351.557

Camera1.k1: -0.05096
Camera1.k2: 0.04872
Camera1.p1: 0.00190
Camera1.p2: 0.00077

# Camera resolution
Camera.width: 960
Camera.height: 720


# Camera frames per second 
Camera.fps: 30

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Transformation from camera to body-frame (imu)
IMU.T_b_c1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [0.015380685880954759, 0.9987802837231801, -0.04691885918983518, 6.248010695786327e-05,
         -0.17925382959809705, 0.0489185228532264, 0.9825858958362241, -2.1121186496078244e-05,
         0.9836826211112241, -0.006702459824761642, 0.17978759121821974, 0.0001265757067624446,
         0.0, 0.0, 0.0, 1.0]

# IMU noise
IMU.NoiseGyro: 0.0073061
IMU.NoiseAcc: 0.007832
IMU.GyroWalk: 0.0002045
IMU.AccWalk: 0.0005368
IMU.Frequency: 19.5

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 17
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5
Viewer.ViewpointF: 500.0