%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Right Camera calibration and distortion parameters (OpenCV)
Camera1.fx: 907.54075982
Camera1.fy: 909.02932191
Camera1.cx: 494.14941499
Camera1.cy: 347.51006866

# distortion parameters
Camera1.k1: -0.035351561546680295
Camera1.k2: 0.06855868163937204
Camera1.p1: 0.00017580215122216657
Camera1.p2: -0.0011034786735252325


# Camera calibration and distortion parameters (OpenCV)
#Camera1.fx: 929.562627
#Camera1.fy: 928.604856
#Camera1.cx: 487.474037
#Camera1.cy: 363.165223

#Camera1.k1: -0.016272
#Camera1.k2: 0.093492
#Camera1.p1: 0.000093
#Camera1.p2: 0.002999
#Camera1.k3: 0.000000

# Camera frames per second
Camera.fps: 30


# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1


# Camera resolution
Camera.width: 960
Camera.height: 720


#Camera.width: 640
#Camera.height: 480


#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per imagecc
ORBextractor.nFeatures: 1000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 12

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0

#System.LoadAtlasFromFile: "mapa_atlas_pokoj" 
#System.SaveAtlasToFile: "mapa_atlas_pokoj"